[supervisord]
nodaemon=true

[program:http]
command=python -c "from toxic_service.server import run_http; run_http()"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
priority=1

[program:grpc]
command=python -c "from toxic_service.server import run_grpc; run_grpc()"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
priority=2
