# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "inference.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0finference.proto\x12\tinference"\'\n\x17TextClassificationInput\x12\x0c\n\x04text\x18\x01 \x01(\t",\n\x18TextClassificationOutput\x12\x10\n\x08is_toxic\x18\x01 \x01(\x08\x32\x64\n\x0eTextClassifier\x12R\n\x07Predict\x12".inference.TextClassificationInput\x1a#.inference.TextClassificationOutputb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "inference_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_TEXTCLASSIFICATIONINPUT"]._serialized_start = 30
    _globals["_TEXTCLASSIFICATIONINPUT"]._serialized_end = 69
    _globals["_TEXTCLASSIFICATIONOUTPUT"]._serialized_start = 71
    _globals["_TEXTCLASSIFICATIONOUTPUT"]._serialized_end = 115
    _globals["_TEXTCLASSIFIER"]._serialized_start = 117
    _globals["_TEXTCLASSIFIER"]._serialized_end = 217
# @@protoc_insertion_point(module_scope)
